services:

  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=site.local
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./app/:/var/www/html/
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./app/:/var/www/html/
    ports:
      - "9000:9000"
    networks:
      - backend

networks:
  frontend:
    external:
      name: proxy_proxy
  backend:
